export enum ActionName {
    CLEAR_PURCHASED_ITEM = 'CLEAR_PURCHASED_ITEM',
    CLEAR_PURCHASED_ITEMS = 'CLEAR_PURCHASED_ITEMS',
    CLEAR_SELECTED_TODO_ITEMS = 'CLEAR_SELECTED_TODO_ITEMS',
    HIDE_ALERT = 'HIDE_ALERT',
    PURCHASE_GROCERY_ITEM = 'PURCHASE_GROCERY_ITEM',
    SELECT_TODO_ITEM = 'SELECT_TODO_ITEM',
    SHOW_ALERT = 'SHOW_ALERT',
    UNSELECT_TODO_ITEM = 'UNSELECT_TODO_ITEM',
}
