name: Test Website

on:
  pull_request:
    paths:
      - "packages/web/**"
      - ".github/workflows/test-web.yml"
    paths-ignore:
      - "packages/web/**/*.md"
      - "packages/web/LICENSE"

concurrency:
  group: test-web-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/web

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Node.js and yarn
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: packages/web/yarn.lock
      - name: Install Modules
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
